# Generated by Django 2.2 on 2020-06-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='like_time',
            new_name='liked_time',
        ),
    ]
