# Generated by Django 2.2 on 2020-06-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_readed_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
