# Generated by Django 2.2 on 2020-06-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200620_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
